IDVA6-1618-IDVA6-1980 - reformatting and updating dashboard content
companieshouse/acsp-manage-users-web pull request #146
Opened 2024-12-12 11:45 UTC by bwallace-ch

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1980
https://companieshouse.atlassian.net/browse/IDVA6-1618

Changes:
- Reformatted the dashboard templates to follow new prototype design
- Updating language file content to reflect new prototype content
- Updated relevant unit tests
- Added new dashboard box 'close authorised agent'
- Implemented updated stylings

2024-12-12 12:01 UTC, ch-code-analysis commented
CI: No security warnings found

2024-12-12 16:38 UTC, mmodzelewski-ch requested changes

2024-12-12 16:38 UTC, mmodzelewski-ch commented on locales/cy/dashboard.json
> +    "add_users_if_they_need_to_use_services_for": "[CY] add users if they need to use services for the authorised agent",
Could you please sort alphabetically the language json files?

2024-12-13 09:12 UTC, ch-code-analysis commented
CI: No security warnings found

2024-12-13 09:22 UTC, mmodzelewski-ch approved these changes

2024-12-13 10:46 UTC, merged