IDVA6 1180 Add user page
companieshouse/acsp-manage-users-web pull request #28
Opened 2024-07-09 14:25 UTC by bmchugh-ch

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1180

Changes:

Adds the "add user" page including forms, validation and session handling. See IDVA6-1180 for more information.

2024-07-09 14:55 UTC, mmodzelewski-ch requested changes

2024-07-09 14:55 UTC, mmodzelewski-ch commented on src/lib/validation/add.user.validation.ts
> +export const addErrorToViewData = (
This function could be moved to `src/lib/utils/viewUtils.ts`

2024-07-09 14:55 UTC, mmodzelewski-ch commented on src/locales/en/translation/add-user.json
> +{
There is no Welsh version json created

2024-07-09 14:55 UTC, mmodzelewski-ch commented on src/locales/en/translation/common.json
> +    "back_link_to_the_previous_page": "Back link to the previous page",
The Welsh version json is not updated

2024-07-09 16:16 UTC, ch-code-analysis commented
CI: No security warnings found

2024-07-09 16:50 UTC, ch-code-analysis commented
CI: No security warnings found

2024-07-10 08:18 UTC, mmodzelewski-ch approved these changes

2024-07-12 15:37 UTC, ch-code-analysis commented
CI: No security warnings found

2024-07-12 15:52 UTC, merged